-- Common Philippine credentials for faculty profiles, reviewed 2026-10-01.
-- This is a selection catalog, not a determination of credential validity.
CREATE TABLE IF NOT EXISTS tbl_faculty_eligibilities (
  eligibility_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code VARCHAR(80) NOT NULL,
  name VARCHAR(200) NOT NULL,
  category VARCHAR(80) NOT NULL,
  issuing_body VARCHAR(80) NOT NULL,
  search_terms VARCHAR(500) NOT NULL DEFAULT '',
  source_url VARCHAR(500) NOT NULL,
  sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (eligibility_id),
  UNIQUE KEY uniq_faculty_eligibility_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS tbl_faculty_profile_eligibilities (
  user_id INT NOT NULL,
  eligibility_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (user_id, eligibility_id),
  KEY idx_profile_eligibility (eligibility_id),
  CONSTRAINT fk_profile_eligibility_profile FOREIGN KEY (user_id)
    REFERENCES tbl_faculty_profiles (user_id) ON DELETE CASCADE,
  CONSTRAINT fk_profile_eligibility_catalog FOREIGN KEY (eligibility_id)
    REFERENCES tbl_faculty_eligibilities (eligibility_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO tbl_faculty_eligibilities
  (code, name, category, issuing_body, search_terms, source_url, sort_order)
VALUES
  ('csc_professional', 'Career Service Professional Eligibility', 'Civil service eligibility', 'CSC', 'CSC CSE professional second level', 'https://csc.gov.ph/special-eligibilities', 10),
  ('csc_subprofessional', 'Career Service Subprofessional Eligibility', 'Civil service eligibility', 'CSC', 'CSC CSE sub-professional first level', 'https://csc.gov.ph/special-eligibilities', 10),
  ('csc_ra1080', 'Bar / Board Eligibility (RA 1080)', 'Civil service eligibility', 'CSC', 'RA1080 board bar', 'https://csc.gov.ph/special-eligibilities', 10),
  ('csc_honor', 'Honor Graduate Eligibility (PD 907)', 'Civil service eligibility', 'CSC', 'HGE cum laude magna summa', 'https://csc.gov.ph/special-eligibilities', 10),
  ('csc_foreign_honor', 'Foreign School Honor Graduate Eligibility', 'Civil service eligibility', 'CSC', 'FSHGE', 'https://csc.gov.ph/special-eligibilities', 10),
  ('csc_edp', 'Electronic Data Processing Specialist Eligibility', 'Civil service eligibility', 'CSC', 'EDPSE DICT ICT computer programming systems analysis', 'https://csc.gov.ph/special-eligibilities', 10),
  ('csc_science', 'Scientific and Technological Specialist Eligibility (PD 997)', 'Civil service eligibility', 'CSC', 'STSE DOST', 'https://csc.gov.ph/special-eligibilities', 10),
  ('csc_skills', 'Skills Eligibility - Category II', 'Civil service eligibility', 'CSC', 'skills trade', 'https://csc.gov.ph/special-eligibilities', 10),
  ('csc_barangay', 'Barangay Official Eligibility', 'Civil service eligibility', 'CSC', 'BOE', 'https://csc.gov.ph/special-eligibilities', 10),
  ('csc_health_worker', 'Barangay Health Worker Eligibility', 'Civil service eligibility', 'CSC', 'BHWE', 'https://csc.gov.ph/special-eligibilities', 10),
  ('csc_nutrition', 'Barangay Nutrition Scholar Eligibility', 'Civil service eligibility', 'CSC', 'BNSE', 'https://csc.gov.ph/special-eligibilities', 10),
  ('csc_sanggunian', 'Sanggunian Member Eligibility', 'Civil service eligibility', 'CSC', 'SME', 'https://csc.gov.ph/special-eligibilities', 10),
  ('csc_sk', 'Sanggunian Kabataan Officials Eligibility', 'Civil service eligibility', 'CSC', 'SKOE SK', 'https://csc.gov.ph/special-eligibilities', 10),
  ('csc_veteran', 'Veteran Preference Rating', 'Civil service eligibility', 'CSC', 'VPR', 'https://csc.gov.ph/special-eligibilities', 10),
  ('csc_preference', 'Career Service Eligibility - Preference Rating', 'Civil service eligibility', 'CSC', 'CSE-PR', 'https://csc.gov.ph/special-eligibilities', 10),
  ('csc_ofw', 'Overseas Filipino Workers - Preference Rating', 'Civil service eligibility', 'CSC', 'OFW-PR', 'https://csc.gov.ph/special-eligibilities', 10),
  ('csc_fire', 'Fire Officer Eligibility', 'Civil service eligibility', 'CSC', 'FOE', 'https://csc.gov.ph/csc-opens-applications-for-local-treasury-fire-officer-penology-officer-exams', 20),
  ('csc_penology', 'Penology Officer Eligibility', 'Civil service eligibility', 'CSC', 'POE', 'https://csc.gov.ph/csc-opens-applications-for-local-treasury-fire-officer-penology-officer-exams', 20),
  ('csc_treasury', 'Local Treasurer Eligibility', 'Civil service eligibility', 'CSC', 'BCLTE treasury', 'https://csc.gov.ph/csc-opens-applications-for-local-treasury-fire-officer-penology-officer-exams', 20),
  ('prc_teacher', 'Licensed Professional Teacher', 'PRC professional licenses', 'PRC', 'LPT LET LEPT professional teacher board examination teachers', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_accountant', 'Certified Public Accountant', 'PRC professional licenses', 'PRC', 'CPA accountancy', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_aeronautical', 'Aeronautical Engineer', 'PRC professional licenses', 'PRC', 'aeronautical engineering', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_agricultural', 'Agricultural and Biosystems Engineer', 'PRC professional licenses', 'PRC', 'agricultural engineer ABE', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_agriculturist', 'Agriculturist', 'PRC professional licenses', 'PRC', 'agriculture', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_architect', 'Architect', 'PRC professional licenses', 'PRC', 'architecture', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_chemical_engineer', 'Chemical Engineer', 'PRC professional licenses', 'PRC', 'chemical engineering', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_chemist', 'Chemist', 'PRC professional licenses', 'PRC', 'chemistry', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_chemical_technician', 'Chemical Technician', 'PRC professional licenses', 'PRC', 'chemistry technician', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_civil', 'Civil Engineer', 'PRC professional licenses', 'PRC', 'CE civil engineering', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_criminologist', 'Criminologist', 'PRC professional licenses', 'PRC', 'criminology', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_customs', 'Customs Broker', 'PRC professional licenses', 'PRC', 'customs administration', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_dentist', 'Dentist', 'PRC professional licenses', 'PRC', 'dentistry', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_dental_hygienist', 'Dental Hygienist', 'PRC professional licenses', 'PRC', 'dental hygiene', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_electrical', 'Registered Electrical Engineer', 'PRC professional licenses', 'PRC', 'REE electrical engineering', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_professional_electrical', 'Professional Electrical Engineer', 'PRC professional licenses', 'PRC', 'PEE', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_electrician', 'Registered Master Electrician', 'PRC professional licenses', 'PRC', 'RME electrician', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_electronics', 'Electronics Engineer', 'PRC professional licenses', 'PRC', 'ECE electronics communication', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_environmental', 'Environmental Planner', 'PRC professional licenses', 'PRC', 'EnP planning', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_fisheries', 'Fisheries Technologist', 'PRC professional licenses', 'PRC', 'fisheries', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_food', 'Food Technologist', 'PRC professional licenses', 'PRC', 'food technology', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_forester', 'Forester', 'PRC professional licenses', 'PRC', 'forestry', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_geodetic', 'Geodetic Engineer', 'PRC professional licenses', 'PRC', 'GE surveying', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_geologist', 'Geologist', 'PRC professional licenses', 'PRC', 'geology', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_guidance', 'Guidance Counselor', 'PRC professional licenses', 'PRC', 'RGC guidance counseling', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_interior', 'Interior Designer', 'PRC professional licenses', 'PRC', 'interior design', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_landscape', 'Landscape Architect', 'PRC professional licenses', 'PRC', 'landscape architecture', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_librarian', 'Librarian', 'PRC professional licenses', 'PRC', 'RL librarianship library science', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_plumber', 'Master Plumber', 'PRC professional licenses', 'PRC', 'RMP plumbing', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_mechanical', 'Mechanical Engineer', 'PRC professional licenses', 'PRC', 'ME', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_professional_mechanical', 'Professional Mechanical Engineer', 'PRC professional licenses', 'PRC', 'PME', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_medtech', 'Medical Technologist', 'PRC professional licenses', 'PRC', 'RMT medical technology', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_physician', 'Physician', 'PRC professional licenses', 'PRC', 'MD medicine doctor', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_metallurgical', 'Metallurgical Engineer', 'PRC professional licenses', 'PRC', 'metallurgy', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_midwife', 'Midwife', 'PRC professional licenses', 'PRC', 'RM midwifery', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_mining', 'Mining Engineer', 'PRC professional licenses', 'PRC', 'mining', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_naval', 'Naval Architect', 'PRC professional licenses', 'PRC', 'naval architecture marine engineering', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_nurse', 'Registered Nurse', 'PRC professional licenses', 'PRC', 'RN nursing', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_nutrition', 'Nutritionist-Dietitian', 'PRC professional licenses', 'PRC', 'RND nutrition dietetics', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_occupational', 'Occupational Therapist', 'PRC professional licenses', 'PRC', 'OT occupational therapy', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_optometrist', 'Optometrist', 'PRC professional licenses', 'PRC', 'optometry', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_pharmacist', 'Pharmacist', 'PRC professional licenses', 'PRC', 'RPh pharmacy', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_physical', 'Physical Therapist', 'PRC professional licenses', 'PRC', 'PT physical therapy', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_psychologist', 'Psychologist', 'PRC professional licenses', 'PRC', 'RPsy psychology', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_radiologic', 'Radiologic Technologist', 'PRC professional licenses', 'PRC', 'RRT radiologic technology', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_real_estate_appraiser', 'Real Estate Appraiser', 'PRC professional licenses', 'PRC', 'real estate', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_real_estate_broker', 'Real Estate Broker', 'PRC professional licenses', 'PRC', 'real estate', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_real_estate_consultant', 'Real Estate Consultant', 'PRC professional licenses', 'PRC', 'real estate', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_respiratory', 'Respiratory Therapist', 'PRC professional licenses', 'PRC', 'respiratory therapy', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_sanitary', 'Sanitary Engineer', 'PRC professional licenses', 'PRC', 'sanitary engineering', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_social', 'Social Worker', 'PRC professional licenses', 'PRC', 'RSW social work', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_speech', 'Speech-Language Pathologist', 'PRC professional licenses', 'PRC', 'SLP speech language pathology', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_veterinarian', 'Veterinarian', 'PRC professional licenses', 'PRC', 'DVM veterinary medicine', 'https://www.prc.gov.ph/professional-regulatory-boards', 30),
  ('prc_dental_technologist', 'Dental Technologist', 'PRC professional licenses', 'PRC', 'dental technology', 'https://www.prc.gov.ph/article/prc-cdo-board-certificate-release/1520', 40),
  ('prc_electronics_technician', 'Electronics Technician', 'PRC professional licenses', 'PRC', 'ECT', 'https://www.prc.gov.ph/article/prc-cdo-board-certificate-release/1520', 40),
  ('prc_professional_electronics', 'Professional Electronics Engineer', 'PRC professional licenses', 'PRC', 'PECE', 'https://www.prc.gov.ph/article/prc-cdo-board-certificate-release/1520', 40),
  ('prc_plant_mechanic', 'Certified Plant Mechanic', 'PRC professional licenses', 'PRC', 'CPM', 'https://www.prc.gov.ph/article/prc-cdo-board-certificate-release/1520', 40),
  ('prc_medlab', 'Medical Laboratory Technician', 'PRC professional licenses', 'PRC', 'laboratory', 'https://www.prc.gov.ph/article/prc-cdo-board-certificate-release/1520', 40),
  ('prc_psychometrician', 'Psychometrician', 'PRC professional licenses', 'PRC', 'RPm psychology', 'https://www.prc.gov.ph/article/prc-cdo-board-certificate-release/1520', 40),
  ('prc_xray', 'X-Ray Technologist', 'PRC professional licenses', 'PRC', 'xray technology', 'https://www.prc.gov.ph/article/prc-cdo-board-certificate-release/1520', 40),
  ('sc_lawyer', 'Lawyer / Member of the Philippine Bar', 'Other government credentials', 'Supreme Court', 'attorney bar admission legal', 'https://sc.judiciary.gov.ph/new-lawyers-sign-roll-of-attorneys/', 50),
  ('ces_eligibility', 'Career Executive Service Eligibility', 'Other government credentials', 'CESB / CSC', 'CES CESB', 'https://www.cesboard.gov.ph/2018/index.php?title=Documents%2FEligibility+and+Rank+Appointment%2Ferad.php', 60),
  ('csee_eligibility', 'Career Service Executive Eligibility', 'Other government credentials', 'CESB / CSC', 'CSEE CSC', 'https://www.cesboard.gov.ph/2018/index.php?title=Documents%2FEligibility+and+Rank+Appointment%2Ferad.php', 60),
  ('pnp_entrance', 'PNP Entrance Eligibility', 'Other government credentials', 'NAPOLCOM', 'NAPOLCOM PNPE police', 'https://www.napolcom.gov.ph/r1/index-services.php', 70),
  ('pnp_promotional', 'PNP Promotional Eligibility', 'Other government credentials', 'NAPOLCOM', 'NAPOLCOM PROMEX police promotional', 'https://www.napolcom.gov.ph/r1/index-services.php', 70),
  ('pnp_executive', 'Police Executive Service Eligibility', 'Other government credentials', 'NAPOLCOM', 'PESE NAPOLCOM', 'https://www.napolcom.gov.ph/r1/index-services.php', 70),
  ('tesda_tm1', 'Trainers Methodology Level I (Trainer/Assessor)', 'TESDA certificates', 'TESDA', 'TM I TM1 trainer assessor', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_tm2', 'Trainers Methodology Level II (Training Designer/Developer)', 'TESDA certificates', 'TESDA', 'TM II TM2', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_css', 'Computer Systems Servicing NC II', 'TESDA certificates', 'TESDA', 'CSS NC2 computer hardware', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_java', 'Programming (JAVA) NC III', 'TESDA certificates', 'TESDA', 'Java software', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_dotnet', 'Programming (.Net Technology) NC III', 'TESDA certificates', 'TESDA', 'dotnet software', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_oracle', 'Programming (Oracle Database) NC III', 'TESDA certificates', 'TESDA', 'Oracle database', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_web', 'Web Development NC III', 'TESDA certificates', 'TESDA', 'website development', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_animation', 'Animation NC II', 'TESDA certificates', 'TESDA', 'animation', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_graphic', 'Visual Graphic Design NC III', 'TESDA certificates', 'TESDA', 'graphic design', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_drafting', 'Technical Drafting NC II', 'TESDA certificates', 'TESDA', 'CAD drawing', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_electrical', 'Electrical Installation and Maintenance NC II', 'TESDA certificates', 'TESDA', 'EIM electrician', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_electronics', 'Electronic Products Assembly and Servicing NC II', 'TESDA certificates', 'TESDA', 'EPAS electronics', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_mechatronics', 'Mechatronics Servicing NC II', 'TESDA certificates', 'TESDA', 'mechatronics', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_driving', 'Driving NC II', 'TESDA certificates', 'TESDA', 'driver', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_bookkeeping', 'Bookkeeping NC III', 'TESDA certificates', 'TESDA', 'accounting', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_cookery', 'Cookery NC II', 'TESDA certificates', 'TESDA', 'cooking culinary', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_bread', 'Food Production (Bread and Patisserie) NC II', 'TESDA certificates', 'TESDA', 'baking pastry', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_food_beverage', 'Food and Beverage Services NC II', 'TESDA certificates', 'TESDA', 'FBS hospitality', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_housekeeping', 'Housekeeping NC II', 'TESDA certificates', 'TESDA', 'hospitality', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_front_office', 'Front Office Services NC II', 'TESDA certificates', 'TESDA', 'hotel hospitality', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_tourism', 'Tourism Promotion Services NC II', 'TESDA certificates', 'TESDA', 'tourism', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_caregiving', 'Caregiving NC II', 'TESDA certificates', 'TESDA', 'caregiver', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_agriculture', 'Agricultural Crops Production NC II', 'TESDA certificates', 'TESDA', 'agriculture farming', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_animal', 'Animal Production (Poultry-Chicken) NC II', 'TESDA certificates', 'TESDA', 'animal poultry', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_organic', 'Organic Agriculture Production NC II', 'TESDA certificates', 'TESDA', 'organic farming', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_carpentry', 'Carpentry NC II', 'TESDA certificates', 'TESDA', 'carpentry', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_plumbing', 'Plumbing NC II', 'TESDA certificates', 'TESDA', 'plumber', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_welding', 'Manual Metal Arc Welding (MMAW) NC II', 'TESDA certificates', 'TESDA', 'welding MMAW', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_smaw', 'Shielded Metal Arc Welding (SMAW) NC II (Superseded qualification)', 'TESDA certificates', 'TESDA', 'welding SMAW historical', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_dressmaking', 'Dressmaking NC II', 'TESDA certificates', 'TESDA', 'garments sewing', 'https://www.tesda.gov.ph/Download?SearchTitle=&Searchcat=Training+Regulations', 80),
  ('tesda_nttc', 'National TVET Trainers Certificate', 'TESDA certificates', 'TESDA', 'NTTC trainer', 'https://www.tesda.gov.ph/About/TESDA/25', 90),
  ('tesda_coc', 'Certificate of Competency (COC)', 'TESDA certificates', 'TESDA', 'TESDA COC competency', 'https://www.tesda.gov.ph/About/TESDA/25', 90)
ON DUPLICATE KEY UPDATE name = VALUES(name), category = VALUES(category),
  issuing_body = VALUES(issuing_body), search_terms = VALUES(search_terms),
  source_url = VALUES(source_url), sort_order = VALUES(sort_order);

