-- One faculty profile per login account. The existing faculty link remains
-- in tbl_useraccount_faculty_links; no scheduling or account data is changed.
CREATE TABLE IF NOT EXISTS `tbl_faculty_profiles` (
  `user_id` INT NOT NULL,
  `full_name` VARCHAR(250) NOT NULL,
  `gender` VARCHAR(30) NOT NULL DEFAULT '',
  `date_of_birth` DATE DEFAULT NULL,
  `civil_status` VARCHAR(30) NOT NULL DEFAULT '',
  `campus_name` VARCHAR(200) NOT NULL DEFAULT '',
  `college_name` VARCHAR(200) NOT NULL DEFAULT '',
  `faculty_rank` VARCHAR(150) NOT NULL DEFAULT '',
  `salary_grade` VARCHAR(100) NOT NULL DEFAULT '',
  `employment_classification` VARCHAR(30) NOT NULL DEFAULT '',
  `work_status` VARCHAR(60) NOT NULL DEFAULT '',
  `eligibility` TEXT NOT NULL,
  `service_start_date` DATE DEFAULT NULL,
  `length_of_service` VARCHAR(150) NOT NULL DEFAULT '',
  `bachelor_degree` VARCHAR(500) NOT NULL DEFAULT '',
  `bachelor_institution` VARCHAR(300) NOT NULL DEFAULT '',
  `bachelor_address` VARCHAR(500) NOT NULL DEFAULT '',
  `bachelor_specialization` VARCHAR(500) NOT NULL DEFAULT '',
  `bachelor_status` VARCHAR(30) NOT NULL DEFAULT '',
  `master_degree` VARCHAR(500) NOT NULL DEFAULT '',
  `master_institution` VARCHAR(300) NOT NULL DEFAULT '',
  `master_address` VARCHAR(500) NOT NULL DEFAULT '',
  `master_specialization` VARCHAR(500) NOT NULL DEFAULT '',
  `master_status` VARCHAR(30) NOT NULL DEFAULT '',
  `doctoral_degree` VARCHAR(500) NOT NULL DEFAULT '',
  `doctoral_institution` VARCHAR(300) NOT NULL DEFAULT '',
  `doctoral_address` VARCHAR(500) NOT NULL DEFAULT '',
  `doctoral_specialization` VARCHAR(500) NOT NULL DEFAULT '',
  `doctoral_status` VARCHAR(30) NOT NULL DEFAULT '',
  `revision` INT UNSIGNED NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_faculty_profile_account` FOREIGN KEY (`user_id`)
    REFERENCES `tbl_useraccount` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
