CREATE TABLE IF NOT EXISTS `tbl_useraccount_registrar_scopes` (
  `account_registrar_scope_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `campus_id` INT UNSIGNED NOT NULL,
  `is_default` TINYINT(1) NOT NULL DEFAULT 1,
  `status` VARCHAR(20) NOT NULL DEFAULT 'active',
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`account_registrar_scope_id`),
  UNIQUE KEY `uniq_registrar_user_campus` (`user_id`, `campus_id`),
  KEY `idx_registrar_scope_user` (`user_id`),
  KEY `idx_registrar_scope_campus` (`campus_id`),
  KEY `idx_registrar_scope_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tbl_enrollment_headers` (
  `enrollment_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `enrollment_reference` VARCHAR(60) NOT NULL,
  `workflow_status` VARCHAR(20) NOT NULL DEFAULT 'draft',
  `campus_id` INT UNSIGNED NOT NULL,
  `college_id` INT UNSIGNED NOT NULL,
  `program_id` INT UNSIGNED NOT NULL,
  `section_id` INT UNSIGNED NOT NULL,
  `ay_id` INT UNSIGNED NOT NULL,
  `semester` TINYINT UNSIGNED NOT NULL,
  `year_level` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `enrollment_type` VARCHAR(30) NOT NULL DEFAULT 'regular',
  `student_record_mode` VARCHAR(30) NOT NULL DEFAULT 'first_year',
  `student_id` INT UNSIGNED DEFAULT NULL,
  `student_number` VARCHAR(50) DEFAULT NULL,
  `last_name` VARCHAR(120) DEFAULT NULL,
  `first_name` VARCHAR(120) DEFAULT NULL,
  `middle_name` VARCHAR(120) DEFAULT NULL,
  `suffix_name` VARCHAR(50) DEFAULT NULL,
  `sex` VARCHAR(20) DEFAULT NULL,
  `birthdate` DATE DEFAULT NULL,
  `email_address` VARCHAR(190) DEFAULT NULL,
  `contact_number` VARCHAR(50) DEFAULT NULL,
  `verification_note` TEXT DEFAULT NULL,
  `chair_notes` TEXT DEFAULT NULL,
  `registrar_notes` TEXT DEFAULT NULL,
  `created_by` INT UNSIGNED NOT NULL,
  `submitted_by` INT UNSIGNED DEFAULT NULL,
  `reviewed_by` INT UNSIGNED DEFAULT NULL,
  `approved_by` INT UNSIGNED DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `submitted_at` DATETIME DEFAULT NULL,
  `reviewed_at` DATETIME DEFAULT NULL,
  `approved_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`enrollment_id`),
  UNIQUE KEY `uniq_enrollment_reference` (`enrollment_reference`),
  KEY `idx_enrollment_created_by` (`created_by`),
  KEY `idx_enrollment_scope_term` (`campus_id`, `college_id`, `program_id`, `ay_id`, `semester`),
  KEY `idx_enrollment_section` (`section_id`),
  KEY `idx_enrollment_status` (`workflow_status`),
  KEY `idx_enrollment_student_number` (`student_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tbl_enrollment_subjects` (
  `enrollment_subject_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `enrollment_id` INT UNSIGNED NOT NULL,
  `offering_id` INT UNSIGNED NOT NULL,
  `subject_id` INT UNSIGNED DEFAULT NULL,
  `subject_code` VARCHAR(60) DEFAULT NULL,
  `descriptive_title` VARCHAR(255) DEFAULT NULL,
  `units` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  `section_text` VARCHAR(120) DEFAULT NULL,
  `schedule_text` TEXT DEFAULT NULL,
  `room_text` VARCHAR(255) DEFAULT NULL,
  `faculty_text` VARCHAR(255) DEFAULT NULL,
  `sort_order` INT UNSIGNED NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`enrollment_subject_id`),
  UNIQUE KEY `uniq_enrollment_subject_offering` (`enrollment_id`, `offering_id`),
  KEY `idx_enrollment_subject_enrollment` (`enrollment_id`),
  KEY `idx_enrollment_subject_subject` (`subject_id`),
  KEY `idx_enrollment_subject_sort` (`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `tbl_enrollment_workflow_logs` (
  `workflow_log_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `enrollment_id` INT UNSIGNED NOT NULL,
  `action_type` VARCHAR(40) NOT NULL,
  `from_status` VARCHAR(20) DEFAULT NULL,
  `to_status` VARCHAR(20) DEFAULT NULL,
  `acted_by_user_id` INT UNSIGNED NOT NULL,
  `acted_by_role` VARCHAR(40) NOT NULL,
  `remarks` TEXT DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`workflow_log_id`),
  KEY `idx_enrollment_log_enrollment` (`enrollment_id`),
  KEY `idx_enrollment_log_actor` (`acted_by_user_id`),
  KEY `idx_enrollment_log_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
